package com.ridelink.network.security

import com.ridelink.core.security.UtcTime
import org.conscrypt.Conscrypt
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.PrivateKey
import java.security.SecureRandom
import java.security.Signature
import java.security.cert.X509Certificate
import java.security.spec.ECGenParameterSpec
import javax.net.ssl.KeyManager
import javax.net.ssl.SSLContext
import javax.net.ssl.SSLSocket
import javax.net.ssl.TrustManager

/**
 * Test doubles for the two things a JVM cannot supply: Android Keystore, and a TLS provider with a
 * keying-material exporter.
 *
 * Both substitutions are narrow and named, and each is the *only* part of the Phase 1b security
 * path that a laptop cannot run for real:
 *
 * | Production | Here | What is still real |
 * |---|---|---|
 * | Android Keystore holds a non-exportable P-256 key | An in-memory `KeyStore` holds a JCE P-256 key | The certificate encoding, the signing call, the `KeyManager` wiring, the SPKI derivation |
 * | Conscrypt via `android.net.ssl.SSLSockets` | Conscrypt directly | The TLS 1.3 handshake, the certificates, the mutual auth, the exporter computation |
 *
 * So what these doubles remove is *where the private key lives* and *which call frame reaches the
 * exporter* — not the cryptography, the wire format or the protocol. What they cannot prove is
 * recorded in `docs/test-results/phase1b-security-spike-20260827.md` §5 and closed by the
 * real-device gate.
 */
object TestTlsSupport {
    private val conscryptProvider = Conscrypt.newProvider()

    /**
     * The exact production [TlsProvider] contract, backed by Conscrypt on the JVM.
     *
     * `Conscrypt.exportKeyingMaterial` is the method `android.net.ssl.SSLSockets.exportKeyingMaterial`
     * delegates to, so this exercises the same computation one call frame lower. The context is
     * passed through unchanged, including the empty array RideLink uses (ADR-018 §2).
     */
    object ConscryptTlsProvider : TlsProvider {
        override fun sslContext(
            keyManagers: Array<KeyManager>,
            trustManagers: Array<TrustManager>,
            random: SecureRandom,
        ): SSLContext =
            SSLContext.getInstance("TLSv1.3", conscryptProvider).apply { init(keyManagers, trustManagers, random) }

        override fun exportKeyingMaterial(
            socket: SSLSocket,
            label: String,
            context: ByteArray,
            length: Int,
        ): ByteArray? = runCatching { Conscrypt.exportKeyingMaterial(socket, label, context, length) }.getOrNull()
    }

    /** A [TlsProvider] whose exporter is unavailable, to prove pairing fails closed rather than degrading. */
    object ExporterlessTlsProvider : TlsProvider {
        override fun sslContext(
            keyManagers: Array<KeyManager>,
            trustManagers: Array<TrustManager>,
            random: SecureRandom,
        ): SSLContext = ConscryptTlsProvider.sslContext(keyManagers, trustManagers, random)

        override fun exportKeyingMaterial(
            socket: SSLSocket,
            label: String,
            context: ByteArray,
            length: Int,
        ): ByteArray? = null
    }

    private val KEY_PASSWORD = CharArray(0) // in-memory keystore, never written to disk
    private const val ALIAS = "test"

    /**
     * A [DeviceIdentity] plus the private key behind it, which production code deliberately has no
     * way to reach. Only [reissue] needs it, and only because re-issuing around an existing key is
     * a behaviour worth testing directly (ADR-012).
     */
    data class TestIdentity(
        val identity: DeviceIdentity,
        val privateKey: PrivateKey,
    )

    /**
     * An identity whose key is generated by the JCE rather than by Android Keystore, and whose
     * certificate is issued by the **production** [IdentityIssuer] — so the encoding, the
     * signature and the SPKI under test are the real ones.
     */
    fun freshIdentity(now: UtcTime = UtcTime(NOW_EPOCH_SECONDS)): TestIdentity {
        val generator = KeyPairGenerator.getInstance(DeviceIdentity.KEY_ALGORITHM)
        generator.initialize(ECGenParameterSpec(DeviceIdentity.CURVE))
        val keyPair = generator.generateKeyPair()
        val signer = Signature.getInstance(DeviceIdentity.SIGNATURE_ALGORITHM).apply { initSign(keyPair.private) }
        return TestIdentity(wrap(IdentityIssuer.issue(keyPair.public, signer, now), keyPair.private), keyPair.private)
    }

    /**
     * Re-issues a certificate around an **existing** key — the ADR-012 case that must stay
     * trusted, and the operation Android's `KeyGenParameterSpec` auto-certificate cannot perform
     * (ADR-017 §3). The SPKI is unchanged by construction, because the key is.
     */
    fun reissue(
        existing: TestIdentity,
        now: UtcTime = UtcTime(NOW_EPOCH_SECONDS + ONE_YEAR_SECONDS),
    ): TestIdentity {
        val signer = Signature.getInstance(DeviceIdentity.SIGNATURE_ALGORITHM).apply { initSign(existing.privateKey) }
        val certificate = IdentityIssuer.issue(existing.identity.certificate.publicKey, signer, now)
        return TestIdentity(wrap(certificate, existing.privateKey), existing.privateKey)
    }

    private fun wrap(
        certificate: X509Certificate,
        privateKey: PrivateKey,
    ): DeviceIdentity {
        val keyStore =
            KeyStore.getInstance(KeyStore.getDefaultType()).apply {
                load(null)
                setKeyEntry(ALIAS, privateKey, KEY_PASSWORD, arrayOf(certificate))
            }
        return DeviceIdentity(certificate, keyStore, ALIAS, KEY_PASSWORD)
    }

    /** 27 August 2026, 12:00 UTC — a fixed instant, so no test depends on when it is run. */
    const val NOW_EPOCH_SECONDS: Long = 1_787_832_000
    const val ONE_YEAR_SECONDS: Long = 365L * 24 * 60 * 60
}
