import Foundation
import GRDB
import RideLinkCore
import XCTest
@testable import RideLinkPlatform

/// The real pipeline — real `AVFoundation`/`ImageIO`, real `CryptoKit` file hashing, real GRDB —
/// against the committed `test-media/synthetic/` fixtures generated by
/// `tools/generate_test_media.py`. The mirror of Android's `LibraryIndexerTest`, run against the
/// exact same fixture files so a platform difference in metadata/artwork extraction shows up as a
/// failing assertion here rather than being discovered on a device.
final class LibraryIndexerTests: XCTestCase {
    private var dbQueue: DatabaseQueue!
    private var repository: LibraryRepository!
    private var indexer: LibraryIndexer!
    private var musicDirectory: URL!
    private var cachesDirectory: URL!
    private let clock = TestClock()

    override func setUpWithError() throws {
        dbQueue = try DatabaseQueue()
        try LibraryDatabase.makeMigrator().migrate(dbQueue)
        repository = LibraryRepository(dbQueue: dbQueue)
        let tempRoot = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        musicDirectory = tempRoot.appendingPathComponent("music")
        cachesDirectory = tempRoot.appendingPathComponent("caches")
        try FileManager.default.createDirectory(at: musicDirectory, withIntermediateDirectories: true)
        try FileManager.default.createDirectory(at: cachesDirectory, withIntermediateDirectories: true)
        indexer = LibraryIndexer(
            repository: repository,
            artworkCache: ArtworkCache(cachesDirectory: cachesDirectory),
            musicDirectory: musicDirectory,
            monotonicNowUs: { [clock] in clock.next() }
        )
    }

    override func tearDownWithError() throws {
        try? FileManager.default.removeItem(at: musicDirectory.deletingLastPathComponent())
    }

    private func firstEntries(query: LibraryQuery = LibraryQuery()) async -> [LibraryEntry] {
        var iterator = repository.observe(query: query).makeAsyncIterator()
        return await iterator.next() ?? []
    }

    /// Writes `bytes` directly to a fresh temp file and returns a `file://` URL for it — used to
    /// construct exact, deterministic byte patterns a pre-baked fixture cannot express concisely.
    /// Mirrors the Android instrumented test's `writeRawFixture`.
    private func writeRawFixture(_ name: String, bytes: Data) throws -> URL {
        let url = FileManager.default.temporaryDirectory.appendingPathComponent("fixture-\(UUID().uuidString)-\(name)")
        try bytes.write(to: url)
        return url
    }

    func testImportingANormalTrackExtractsRealMetadataAndArtwork() async throws {
        try await indexer.importFiles([TestMedia.url("normal.m4a")])
        let entries = await firstEntries()
        XCTAssertEqual(entries.count, 1)
        let entry = try XCTUnwrap(entries.first)
        XCTAssertEqual(entry.track.title, "Test Track")
        XCTAssertEqual(entry.track.artist, "Test Artist")
        XCTAssertEqual(entry.track.album, "Test Album")
        XCTAssertEqual(entry.decodeStatus, .indexed)
        XCTAssertGreaterThan(entry.track.durationMs, 0, "a real AAC file must report a real duration")
        let artworkRef = try XCTUnwrap(entry.track.artworkRef, "normal.m4a has embedded artwork")
        let artworkURL = ArtworkCache(cachesDirectory: cachesDirectory).fileURL(for: artworkRef)
        let artworkSize = try FileManager.default.attributesOfItem(atPath: artworkURL.path)[.size] as? Int ?? 0
        XCTAssertGreaterThan(artworkSize, 0, "the cached artwork file must actually exist")
    }

    func testMissingMetadataFallsBackToFilenameAndUnknownLiterals() async throws {
        try await indexer.importFiles([TestMedia.url("no_metadata.m4a")])
        let entries = await firstEntries()
        let entry = try XCTUnwrap(entries.first)
        XCTAssertEqual(entry.track.title, "no_metadata")
        XCTAssertEqual(entry.track.artist, "Unknown Artist")
        XCTAssertEqual(entry.track.album, "Unknown Album")
    }

    func testUnicodeMetadataRoundTripsThroughRealAVFoundation() async throws {
        try await indexer.importFiles([TestMedia.url("unicode_metadata.m4a")])
        let entries = await firstEntries()
        let entry = try XCTUnwrap(entries.first)
        XCTAssertTrue(entry.track.title.contains("楽曲"), "Japanese title text must survive the real platform decoder")
        XCTAssertTrue(entry.track.album.contains("專輯"), "Traditional Chinese album text must survive the real platform decoder")
    }

    func testNoArtworkLeavesArtworkRefNil() async throws {
        try await indexer.importFiles([TestMedia.url("no_artwork.m4a")])
        let entries = await firstEntries()
        let entry = try XCTUnwrap(entries.first)
        XCTAssertNil(entry.track.artworkRef)
    }

    func testByteIdenticalDuplicatesAtTwoLocationsRemainTwoIndependentEntries() async throws {
        // ADR-005 Amendment A1: Phase 3 no longer collapses rows by QuickId at index time — real,
        // authoritative duplicate collapsing (FR-010) is Phase 4/5 transfer scope, keyed on
        // ContentHash once both sides have it, never performed eagerly here. Two byte-identical
        // files at two different locations are, correctly, two independent local library rows in
        // Phase 3's catalogue.
        try await indexer.importFiles([TestMedia.url("duplicate_a.m4a"), TestMedia.url("duplicate_b.m4a")])
        let entries = await firstEntries()
        XCTAssertEqual(entries.count, 2, "two byte-identical files at two locations must remain two independent rows")
        XCTAssertEqual(Set(entries.map(\.localEntryId)).count, 2, "each location must have its own distinct identity")
        XCTAssertEqual(Set(entries.map(\.track.quickId)).count, 1, "both really do share one QuickId, as byte-identical files should")
    }

    func testTwoFilesSharingAQuickIdButDifferingInTheMiddleAreNeverCollapsedIntoOneEntry() async throws {
        // ADR-005 Amendment A1 / this phase's closure-audit CRITICAL finding, reproduced with real
        // bytes through the real indexing pipeline. QuickId = SHA-256(size || first 64 KiB ||
        // last 64 KiB) samples only part of the file: two files over 128 KiB with the same size and
        // identical first/last 64 KiB windows but a different middle collide onto the same QuickId
        // while being genuinely different content. This is not a SHA-256 collision — it is a
        // deterministic, constructible consequence of sampling, reproduced exactly here rather than
        // hoped for.
        let windowSize = 64 * 1024
        let shared = Data((0..<windowSize).map { UInt8($0 % 256) })
        let middleA = Data(repeating: 0xAA, count: 4096)
        let middleB = Data(repeating: 0xBB, count: 4096)
        let bytesA = shared + middleA + shared
        let bytesB = shared + middleB + shared
        XCTAssertEqual(bytesA.count, bytesB.count)
        XCTAssertGreaterThan(bytesA.count, 128 * 1024, "the fixture must exceed ADR-005's 128 KiB small-file threshold")

        let urlA = try writeRawFixture("collision_a.m4a", bytes: bytesA)
        let urlB = try writeRawFixture("collision_b.m4a", bytes: bytesB)

        let quickIdA = try ContentHashing.computeQuickId(fileURL: urlA)
        let quickIdB = try ContentHashing.computeQuickId(fileURL: urlB)
        XCTAssertEqual(quickIdA, quickIdB, "the two fixtures must share a QuickId for this test to be meaningful")

        let contentHashA = try ContentHashing.computeContentHash(fileURL: urlA)
        let contentHashB = try ContentHashing.computeContentHash(fileURL: urlB)
        XCTAssertNotEqual(contentHashA, contentHashB, "different middle bytes must produce different ContentHash — proves this is not a SHA-256 collision")

        try await indexer.importFiles([urlA, urlB])
        let entries = await firstEntries()
        XCTAssertEqual(entries.count, 2, "two different files sharing a QuickId must never collapse into one library row")
        XCTAssertEqual(Set(entries.map(\.localEntryId)).count, 2, "each must keep its own distinct LocalEntryId")
        XCTAssertEqual(Set(entries.map(\.track.quickId)).count, 1, "confirms both really do share the same QuickId")

        // Once the authoritative hash is known for both, they are still correctly distinguishable —
        // the background pass must not accidentally merge them either.
        try await indexer.completeContentHashing()
        let hashed = await firstEntries()
        XCTAssertEqual(hashed.count, 2)
        XCTAssertEqual(Set(hashed.compactMap(\.track.contentHash)).count, 2, "the two rows' authoritative hashes must differ")
    }

    func testSameMetadataDifferentContentDoesNotDedup() async throws {
        try await indexer.importFiles([
            TestMedia.url("same_metadata_different_bytes_a.m4a"),
            TestMedia.url("same_metadata_different_bytes_b.m4a"),
        ])
        let entries = await firstEntries()
        XCTAssertEqual(entries.count, 2, "identical tags over genuinely different audio must not be deduplicated")
        XCTAssertEqual(Set(entries.map(\.track.title)), ["Shared Title"])
    }

    func testATruncatedRealFileIsClassifiedCorruptNotCrashed() async throws {
        try await indexer.importFiles([TestMedia.url("corrupt.m4a")])
        let entries = await firstEntries()
        let entry = try XCTUnwrap(entries.first)
        XCTAssertEqual(entry.decodeStatus, .corrupt)
    }

    func testAnUnrecognizedExtensionIsClassifiedUnsupportedNeverOpened() async throws {
        try await indexer.importFiles([TestMedia.url("unsupported.xyz")])
        let entries = await firstEntries()
        let entry = try XCTUnwrap(entries.first)
        XCTAssertEqual(entry.decodeStatus, .unsupported)
    }

    func testTheHandBuiltMp3IsRecognizedByExtension() async throws {
        // minimal.mp3's audio payload is documented as not a verified decodable fixture (see
        // tools/generate_test_media.py's docstring); this only proves the extension gate lets it
        // through without the pipeline crashing, whatever DecodeStatus a given decoder assigns it.
        try await indexer.importFiles([TestMedia.url("minimal.mp3")])
        let entries = await firstEntries()
        XCTAssertEqual(entries.count, 1)
    }

    func testImportingTheSameFileTwiceUpdatesRatherThanDuplicates() async throws {
        let url = try TestMedia.url("normal.m4a")
        try await indexer.importFiles([url])
        try await indexer.importFiles([url])
        let entries = await firstEntries()
        XCTAssertEqual(entries.count, 1, "the same source location reimported must update, not duplicate, its row")
    }

    func testSearchMatchesRealImportedMetadataCaseInsensitively() async throws {
        try await indexer.importFiles([TestMedia.url("normal.m4a")])
        let byTitle = await firstEntries(query: LibraryQuery(searchText: "test track"))
        XCTAssertEqual(byTitle.count, 1)
        let byArtist = await firstEntries(query: LibraryQuery(searchText: "TEST ARTIST"))
        XCTAssertEqual(byArtist.count, 1)
        let none = await firstEntries(query: LibraryQuery(searchText: "nonexistent"))
        XCTAssertEqual(none.count, 0)
    }

    func testAFolderImportSkipsFilesWithUnsupportedExtensionsSilently() async throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent("tree-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }
        try FileManager.default.copyItem(at: TestMedia.url("normal.m4a"), to: root.appendingPathComponent("song.m4a"))
        try FileManager.default.copyItem(at: TestMedia.url("unsupported.xyz"), to: root.appendingPathComponent("notes.xyz"))

        try await indexer.importFolder(root)
        let entries = await firstEntries()
        XCTAssertEqual(entries.map(\.track.filename), ["song.m4a"])
    }

    func testSubfolderTraversalFindsNestedTracks() async throws {
        let root = FileManager.default.temporaryDirectory.appendingPathComponent("nested-\(UUID().uuidString)")
        let sub = root.appendingPathComponent("subfolder")
        try FileManager.default.createDirectory(at: sub, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }
        try FileManager.default.copyItem(at: TestMedia.url("normal.m4a"), to: sub.appendingPathComponent("nested.m4a"))

        try await indexer.importFolder(root)
        let entries = await firstEntries()
        XCTAssertEqual(entries.map(\.track.filename), ["nested.m4a"])
    }

    func testCompleteContentHashingFillsInTheLazyHashWithoutChangingIdentity() async throws {
        try await indexer.importFiles([TestMedia.url("normal.m4a")])
        let beforeEntries = await firstEntries()
        let before = try XCTUnwrap(beforeEntries.first)
        XCTAssertNil(before.track.contentHash, "the fast indexing path must not compute the full hash")
        try await indexer.completeContentHashing()
        let afterEntries = await firstEntries()
        let after = try XCTUnwrap(afterEntries.first)
        XCTAssertNotNil(after.track.contentHash)
        XCTAssertEqual(before.localEntryId, after.localEntryId, "hashing must not change this row's identity")
        XCTAssertEqual(before.track.quickId, after.track.quickId)
    }

    func testCompleteContentHashingReadsTheRepositoryDirectlyRatherThanACallerSnapshot() async throws {
        // This phase's closure-audit hardening pass (Finding B): completeContentHashing must not
        // depend on a caller-supplied list that could go stale — it must resume exactly whatever the
        // repository currently reports as missing a hash, including rows imported after any snapshot
        // the caller might have taken.
        try await indexer.importFiles([TestMedia.url("normal.m4a"), TestMedia.url("no_artwork.m4a")])
        let beforeCount = await firstEntries().filter { $0.track.contentHash == nil }.count
        XCTAssertEqual(beforeCount, 2)
        try await indexer.completeContentHashing()
        let afterCount = await firstEntries().filter { $0.track.contentHash == nil }.count
        XCTAssertEqual(afterCount, 0)
        // A second call with nothing left to do must not fail or touch anything.
        try await indexer.completeContentHashing()
        let stillZero = await firstEntries().filter { $0.track.contentHash == nil }.count
        XCTAssertEqual(stillZero, 0)
    }
}

/// A tiny `Sendable` monotonic counter — `LibraryIndexerTests` itself is not `Sendable` (XCTestCase
/// isn't), so `monotonicNowUs`'s `@Sendable` closure needs something else to capture. `@unchecked`
/// is safe here: every test in this file awaits each indexer call before the next, so there is never
/// concurrent access to `value`.
private final class TestClock: @unchecked Sendable {
    private var value: Int64 = 0
    func next() -> Int64 {
        value += 1
        return value
    }
}
