import Foundation

/// Locates the shared synthetic audio fixtures at `test-media/synthetic/` (repo root) — the same
/// files `android/data/src/androidTest/kotlin/.../LibraryIndexerTest.kt` runs against, generated by
/// `tools/generate_test_media.py`, never real music (see `test-media/LICENSE-fixtures.md`).
///
/// A deliberate twin of `Vectors`' loader, same `#filePath` upward-walk technique, pointed at
/// `test-media/synthetic` instead of `protocol/vectors` — one package's test target cannot import
/// another's, so this is duplicated rather than shared, exactly like `Vectors` already is between
/// `RideLinkCoreTests` and `RideLinkPlatformTests`.
enum TestMedia {
    enum TestMediaError: Error {
        case repoRootNotFound
    }

    private static func repoRoot(from callerFilePath: String = #filePath) throws -> URL {
        var dir = URL(fileURLWithPath: callerFilePath).deletingLastPathComponent()
        let fileManager = FileManager.default
        while true {
            let candidate = dir.appendingPathComponent("test-media/synthetic")
            if fileManager.fileExists(atPath: candidate.path) { return dir }
            let parent = dir.deletingLastPathComponent()
            if parent.path == dir.path { throw TestMediaError.repoRootNotFound }
            dir = parent
        }
    }

    /// @return the real file URL for a fixture name (e.g. `"normal.m4a"`) under `test-media/synthetic/`.
    static func url(_ filename: String) throws -> URL {
        try repoRoot().appendingPathComponent("test-media/synthetic").appendingPathComponent(filename)
    }
}
