import Foundation

/// Matches CLAUDE.md's logging redaction rule: ephemeral hex identifiers show 6 characters.
private let voiceRedactedPrefixLen = 6

/// PROTOCOL §7.2 — the **generation guard**. 32 lowercase hex characters (16 CSPRNG bytes),
/// generated by the offerer per negotiation and echoed by the answerer.
///
/// Its whole job is that a `VOICE_*` frame from a negotiation that no longer exists can be dropped
/// by comparison rather than by hoping the timing never lines up. Never persisted, never derived
/// from `peer_id`, `session_id` or the identity key — it identifies a *negotiation*, not a peer.
///
/// Same shape as `ConnTiebreak` and redacted the same way, but a distinct type: reusing one random
/// value for two jobs is the mistake ADR-015 warns about, and reusing one *type* for two jobs is how
/// that mistake gets made.
public struct VoiceSessionId: Hashable, Sendable, CustomStringConvertible {
    public let value: String

    public init(_ value: String) {
        precondition(VoiceSessionId.isValid(value), "VoiceSessionId must be 32 lowercase hex characters")
        self.value = value
    }

    public var description: String { "voice:\(value.prefix(voiceRedactedPrefixLen))…" }

    /// Non-trapping constructor for a value that arrives **off the wire**. Uppercase hex is rejected
    /// rather than normalised — one canonical form, as for `identity_spki_sha256`.
    public static func parse(_ value: String) -> VoiceSessionId? {
        isValid(value) ? VoiceSessionId(value) : nil
    }

    private static func isValid(_ s: String) -> Bool {
        s.count == 32 && s.allSatisfy { $0.isHexDigit && !$0.isUppercase }
    }
}

/// PROTOCOL §7.4 `VOICE_STATE.state`. Exactly the six wire values, plus forward-compatible `unknown`.
public enum VoiceWireState: String, Sendable, Equatable, CaseIterable {
    case idle
    case negotiating
    case connecting
    case active
    case failed
    case closed

    /// A `state` value this build does not recognise. PROTOCOL §7.4: tolerated as `unknown` rather
    /// than making the frame malformed, matching §4.3.1's rule for audio vocabulary.
    case unknown

    public var wire: String { rawValue }

    public static func parse(_ value: String) -> VoiceWireState {
        allCases.first { $0.wire == value && $0 != .unknown } ?? .unknown
    }
}

/// PROTOCOL §7.4 `VOICE_STATE.mode` — the intercom modes of REQUIREMENTS §8.
public enum VoiceMode: String, Sendable, Equatable, CaseIterable {
    case continuous
    case vox
    case ptt

    /// Forward compatibility, exactly as for `VoiceWireState.unknown`.
    case unknown

    public var wire: String { rawValue }

    public static func parse(_ value: String) -> VoiceMode {
        allCases.first { $0.wire == value && $0 != .unknown } ?? .unknown
    }
}

/// PROTOCOL §7.5 — defensive bounds, enforced **before** any peer-supplied string reaches the media
/// stack. Sized from measured RideLink SDP, not guessed, and all far below
/// `MAX_CONTROL_FRAME_BYTES`, so a `VOICE_*` frame is rejected by its own bound long before the frame
/// cap matters.
public enum VoiceBounds {
    public static let maxSdpBytes = 16_384
    public static let maxCandidateBytes = 512
    public static let maxSdpMidBytes = 64
    public static let maxMlineIndex = 31
    public static let maxQueuedCandidates = 64
}

/// The four PROTOCOL §3 voice message types. Deliberately a closed set — there is no `VOICE_END`.
public enum VoiceMessageTypes {
    public static let offer = "VOICE_OFFER"
    public static let answer = "VOICE_ANSWER"
    public static let ice = "VOICE_ICE"
    public static let state = "VOICE_STATE"

    public static let all: Set<String> = [offer, answer, ice, state]
}

/// One decoded, bounds-checked voice signalling message (PROTOCOL §7.4).
///
/// Every payload is a plain Swift value type, which is the point: this is the boundary between the
/// wire and the media stack, and nothing WebRTC-shaped crosses it in either direction. On this
/// platform that is not merely tidy — `RTCSessionDescription` and `RTCIceCandidate` are **not**
/// `Sendable`, so under Swift 6 strict concurrency a value leaving a WebRTC callback has to be
/// reduced to primitives inside that callback anyway (ADR-020).
public enum VoiceSignal: Sendable, Equatable {
    case offer(voiceSessionId: VoiceSessionId, sdp: String)
    case answer(voiceSessionId: VoiceSessionId, sdp: String)
    case iceCandidate(
        voiceSessionId: VoiceSessionId,
        candidate: String,
        /// Nullable by design: WebRTC permits a candidate identified by `sdp_mline_index` alone.
        sdpMid: String?,
        sdpMlineIndex: Int
    )
    /// `voiceSessionId` is nil exactly when the sender holds no generation (PROTOCOL §7.4): `idle`,
    /// `closed`, and the answerer's `negotiating` intent, where the offerer has not created one yet.
    case state(
        voiceSessionId: VoiceSessionId?,
        state: VoiceWireState,
        micMuted: Bool,
        mode: VoiceMode
    )

    public var voiceSessionId: VoiceSessionId? {
        switch self {
        case .offer(let id, _): return id
        case .answer(let id, _): return id
        case .iceCandidate(let id, _, _, _): return id
        case .state(let id, _, _, _): return id
        }
    }

    /// The wire `type` this signal is carried as. One place, so the encoder and the tests agree.
    public var messageType: String {
        switch self {
        case .offer: return VoiceMessageTypes.offer
        case .answer: return VoiceMessageTypes.answer
        case .iceCandidate: return VoiceMessageTypes.ice
        case .state: return VoiceMessageTypes.state
        }
    }

    /// Stable discriminator used by the shared vectors, so both platforms name the cases identically.
    public var kindName: String {
        switch self {
        case .offer: return "Offer"
        case .answer: return "Answer"
        case .iceCandidate: return "IceCandidate"
        case .state: return "State"
        }
    }
}

/// Why a `VOICE_*` payload was refused. Recorded in diagnostics; never sent to the peer verbatim.
public enum VoiceSignalRejection: String, Sendable, Equatable {
    case unknownType = "UNKNOWN_TYPE"
    case missingField = "MISSING_FIELD"
    case wrongFieldType = "WRONG_FIELD_TYPE"
    case malformedVoiceSessionId = "MALFORMED_VOICE_SESSION_ID"
    case sdpEmpty = "SDP_EMPTY"
    case sdpTooLarge = "SDP_TOO_LARGE"
    case candidateEmpty = "CANDIDATE_EMPTY"
    case candidateTooLarge = "CANDIDATE_TOO_LARGE"
    case sdpMidTooLarge = "SDP_MID_TOO_LARGE"
    case mlineIndexOutOfRange = "MLINE_INDEX_OUT_OF_RANGE"
}

/// Parses and bounds-checks a `VOICE_*` payload.
///
/// **Total, and non-trapping.** Every peer-controlled field is read through an accessor that returns
/// nil rather than trapping, so no malformed frame can crash the control read loop — the same rule
/// the §2e hardening pass established for `PING`/`PONG` and Phase 1b extended to `HELLO`.
/// PROTOCOL §7.4: a malformed `VOICE_*` frame is dropped, and the control connection survives.
///
/// The Kotlin mirror is `com.ridelink.core.protocol.VoiceSignalCodec`, and both run
/// `protocol/vectors/voice-signal/`.
public enum VoiceSignalCodec {
    public enum Result: Sendable, Equatable {
        case parsed(VoiceSignal)
        case rejected(VoiceSignalRejection)
    }

    public static let fieldVoiceSessionId = "voice_session_id"
    public static let fieldSdp = "sdp"
    public static let fieldCandidate = "candidate"
    public static let fieldSdpMid = "sdp_mid"
    public static let fieldSdpMlineIndex = "sdp_mline_index"
    public static let fieldState = "state"
    public static let fieldMicMuted = "mic_muted"
    public static let fieldMode = "mode"

    public static func parse(type: String, payload: [String: JSONValue]) -> Result {
        switch type {
        case VoiceMessageTypes.offer:
            return parseDescription(payload) { .offer(voiceSessionId: $0, sdp: $1) }
        case VoiceMessageTypes.answer:
            return parseDescription(payload) { .answer(voiceSessionId: $0, sdp: $1) }
        case VoiceMessageTypes.ice:
            return parseIce(payload)
        case VoiceMessageTypes.state:
            return parseState(payload)
        default:
            return .rejected(.unknownType)
        }
    }

    private static func parseDescription(
        _ payload: [String: JSONValue],
        _ build: (VoiceSessionId, String) -> VoiceSignal
    ) -> Result {
        guard let id = requiredVoiceSessionId(payload) else { return rejectVoiceSessionId(payload) }
        guard let sdp = voiceStringField(payload, fieldSdp) else {
            return missingOrWrongType(payload, fieldSdp)
        }
        if let bound = boundedSdp(sdp) { return .rejected(bound) }
        return .parsed(build(id, sdp))
    }

    private static func parseIce(_ payload: [String: JSONValue]) -> Result {
        guard let id = requiredVoiceSessionId(payload) else { return rejectVoiceSessionId(payload) }
        guard let candidate = voiceStringField(payload, fieldCandidate) else {
            return missingOrWrongType(payload, fieldCandidate)
        }
        if candidate.isEmpty { return .rejected(.candidateEmpty) }
        if utf8Size(candidate) > VoiceBounds.maxCandidateBytes { return .rejected(.candidateTooLarge) }

        // `sdp_mid` is legitimately nullable, so an explicit JSON null is accepted and a missing key
        // is treated the same way. A present-but-wrong-typed value is still a rejection.
        var mid: String?
        if let entry = payload[fieldSdpMid], entry != .null {
            guard let asString = entry.voiceString else { return .rejected(.wrongFieldType) }
            if utf8Size(asString) > VoiceBounds.maxSdpMidBytes { return .rejected(.sdpMidTooLarge) }
            mid = asString
        }

        guard let index = voiceIntField(payload, fieldSdpMlineIndex) else {
            return missingOrWrongType(payload, fieldSdpMlineIndex)
        }
        if index < 0 || index > VoiceBounds.maxMlineIndex { return .rejected(.mlineIndexOutOfRange) }
        return .parsed(.iceCandidate(voiceSessionId: id, candidate: candidate, sdpMid: mid, sdpMlineIndex: index))
    }

    private static func parseState(_ payload: [String: JSONValue]) -> Result {
        guard let stateRaw = voiceStringField(payload, fieldState) else {
            return missingOrWrongType(payload, fieldState)
        }
        guard let micMuted = voiceBoolField(payload, fieldMicMuted) else {
            return missingOrWrongType(payload, fieldMicMuted)
        }
        guard let modeRaw = voiceStringField(payload, fieldMode) else {
            return missingOrWrongType(payload, fieldMode)
        }

        // PROTOCOL §7.4: `voice_session_id` is null exactly when the sender does not hold one —
        // `idle`, `closed`, and the answerer's `negotiating` intent, where the offerer has not
        // created a generation yet. Whether a null id is *meaningful* for a given `state` is the
        // negotiation table's decision (`VoiceNegotiation`), not the codec's: one rule, one place.
        var id: VoiceSessionId?
        if let entry = payload[fieldVoiceSessionId], entry != .null {
            guard let asString = entry.voiceString else { return .rejected(.wrongFieldType) }
            guard let parsed = VoiceSessionId.parse(asString) else { return .rejected(.malformedVoiceSessionId) }
            id = parsed
        }
        return .parsed(
            .state(
                voiceSessionId: id,
                state: VoiceWireState.parse(stateRaw),
                micMuted: micMuted,
                mode: VoiceMode.parse(modeRaw)
            )
        )
    }

    private static func boundedSdp(_ sdp: String) -> VoiceSignalRejection? {
        if sdp.isEmpty { return .sdpEmpty }
        if utf8Size(sdp) > VoiceBounds.maxSdpBytes { return .sdpTooLarge }
        return nil
    }

    private static func requiredVoiceSessionId(_ payload: [String: JSONValue]) -> VoiceSessionId? {
        voiceStringField(payload, fieldVoiceSessionId).flatMap(VoiceSessionId.parse)
    }

    /// Distinguishes "the key is absent or the wrong JSON type" from "the key is a string that is not
    /// 32 lowercase hex characters", because the two are different bugs and the diagnostics screen is
    /// where someone will be looking for the difference.
    private static func rejectVoiceSessionId(_ payload: [String: JSONValue]) -> Result {
        if voiceStringField(payload, fieldVoiceSessionId) != nil {
            return .rejected(.malformedVoiceSessionId)
        }
        return missingOrWrongType(payload, fieldVoiceSessionId)
    }

    private static func missingOrWrongType(_ payload: [String: JSONValue], _ key: String) -> Result {
        payload[key] != nil ? .rejected(.wrongFieldType) : .rejected(.missingField)
    }
}

// The field readers below are deliberately file-private free functions rather than members of a
// `JSONValue` extension: `RideLinkPlatform` already carries `stringValue`/`int64Value`/`boolValue`
// extensions of its own, and a second set with the same names visible in both modules would be an
// ambiguity at every use site in the platform layer. Distinct names, no conflict, no refactor of
// working Phase 1b code.

private extension JSONValue {
    var voiceString: String? {
        if case .string(let value) = self { return value }
        return nil
    }
}

private func voiceStringField(_ payload: [String: JSONValue], _ key: String) -> String? {
    payload[key]?.voiceString
}

/// PROTOCOL fields are typed, not stringly-typed: a quoted number is a wrong type, not an int.
/// `Int(exactly:)`, never the trapping `Int(_:)` — a peer-chosen `Double` can be NaN, infinite or out
/// of range, and a `precondition` on wire input is a remotely triggerable crash.
private func voiceIntField(_ payload: [String: JSONValue], _ key: String) -> Int? {
    guard case .number(let value)? = payload[key] else { return nil }
    return Int(exactly: value)
}

private func voiceBoolField(_ payload: [String: JSONValue], _ key: String) -> Bool? {
    guard case .bool(let value)? = payload[key] else { return nil }
    return value
}

/// Bounds are specified in **UTF-8 bytes** (PROTOCOL §7.5), not characters, because that is what the
/// frame actually carries. For ASCII SDP the two agree; for a peer that puts a multi-byte character
/// in a candidate's network-id they do not, and the frame size is the one that matters.
private func utf8Size(_ s: String) -> Int { s.utf8.count }
