package com.ridelink.core.protocol

import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.intOrNull

/** Matches CLAUDE.md's logging redaction rule: ephemeral hex identifiers show 6 characters. */
private const val REDACTED_PREFIX_LEN = 6

/**
 * PROTOCOL §7.2 — the **generation guard**. 32 lowercase hex characters (16 CSPRNG bytes),
 * generated by the offerer per negotiation and echoed by the answerer.
 *
 * Its whole job is that a `VOICE_*` frame from a negotiation that no longer exists can be dropped
 * by comparison rather than by hoping the timing never lines up. Never persisted, never derived
 * from `peer_id`, `session_id` or the identity key — it identifies a *negotiation*, not a peer.
 *
 * Same shape as [com.ridelink.core.model.ConnTiebreak] and redacted the same way, but a distinct
 * type: reusing one random value for two jobs is the mistake ADR-015 warns about, and reusing one
 * *type* for two jobs is how that mistake gets made.
 */
@JvmInline
value class VoiceSessionId(
    val value: String,
) {
    init {
        require(HEX32.matches(value)) { "VoiceSessionId must be 32 lowercase hex characters" }
    }

    override fun toString(): String = "voice:${value.take(REDACTED_PREFIX_LEN)}…"

    companion object {
        private val HEX32 = Regex("^[0-9a-f]{32}$")

        /**
         * Non-throwing constructor for a value that arrives **off the wire**. Uppercase hex is
         * rejected rather than normalised — one canonical form, as for `identity_spki_sha256`.
         */
        fun parse(value: String): VoiceSessionId? = if (HEX32.matches(value)) VoiceSessionId(value) else null
    }
}

/** PROTOCOL §7.4 `VOICE_STATE.state`. Exactly the six wire values, plus forward-compatible [UNKNOWN]. */
enum class VoiceWireState {
    IDLE,
    NEGOTIATING,
    CONNECTING,
    ACTIVE,
    FAILED,
    CLOSED,

    /**
     * A `state` value this build does not recognise. PROTOCOL §7.4: tolerated as `unknown` rather
     * than making the frame malformed, matching §4.3.1's rule for audio vocabulary.
     */
    UNKNOWN,
    ;

    val wire: String get() = name.lowercase()

    companion object {
        fun parse(value: String): VoiceWireState = entries.firstOrNull { it.wire == value && it != UNKNOWN } ?: UNKNOWN
    }
}

/** PROTOCOL §7.4 `VOICE_STATE.mode` — the intercom modes of REQUIREMENTS §8. */
enum class VoiceMode {
    CONTINUOUS,
    VOX,
    PTT,

    /** Forward compatibility, exactly as for [VoiceWireState.UNKNOWN]. */
    UNKNOWN,
    ;

    val wire: String get() = name.lowercase()

    companion object {
        fun parse(value: String): VoiceMode = entries.firstOrNull { it.wire == value && it != UNKNOWN } ?: UNKNOWN
    }
}

/**
 * PROTOCOL §7.5 — defensive bounds, enforced **before** any peer-supplied string reaches the media
 * stack. Sized from measured RideLink SDP, not guessed, and all far below
 * `MAX_CONTROL_FRAME_BYTES`, so a `VOICE_*` frame is rejected by its own bound long before the
 * frame cap matters.
 */
object VoiceBounds {
    const val MAX_SDP_BYTES = 16_384
    const val MAX_CANDIDATE_BYTES = 512
    const val MAX_SDP_MID_BYTES = 64
    const val MAX_MLINE_INDEX = 31
    const val MAX_QUEUED_CANDIDATES = 64
}

/** The four PROTOCOL §3 voice message types. Deliberately a closed set — there is no `VOICE_END`. */
object VoiceMessageTypes {
    const val OFFER = "VOICE_OFFER"
    const val ANSWER = "VOICE_ANSWER"
    const val ICE = "VOICE_ICE"
    const val STATE = "VOICE_STATE"

    val ALL = setOf(OFFER, ANSWER, ICE, STATE)
}

/**
 * One decoded, bounds-checked voice signalling message (PROTOCOL §7.4).
 *
 * Every field is a plain Kotlin primitive, which is the point: this is the boundary between the
 * wire and the media stack, and nothing WebRTC-shaped crosses it in either direction. The same
 * choice makes the iOS side's Swift 6 concurrency work — an `RTCSessionDescription` is not
 * `Sendable`, a `String` is (ADR-020).
 */
sealed class VoiceSignal {
    abstract val voiceSessionId: VoiceSessionId?

    data class Offer(
        override val voiceSessionId: VoiceSessionId,
        val sdp: String,
    ) : VoiceSignal()

    data class Answer(
        override val voiceSessionId: VoiceSessionId,
        val sdp: String,
    ) : VoiceSignal()

    data class IceCandidate(
        override val voiceSessionId: VoiceSessionId,
        val candidate: String,
        /** Nullable by design: WebRTC permits a candidate identified by `sdp_mline_index` alone. */
        val sdpMid: String?,
        val sdpMlineIndex: Int,
    ) : VoiceSignal()

    data class State(
        /**
         * Null exactly when the sender holds no generation (PROTOCOL §7.4): `idle`, `closed`, and
         * the answerer's `negotiating` intent, where the offerer has not created one yet.
         */
        override val voiceSessionId: VoiceSessionId?,
        val state: VoiceWireState,
        val micMuted: Boolean,
        val mode: VoiceMode,
    ) : VoiceSignal()
}

/** Why a `VOICE_*` payload was refused. Recorded in diagnostics; never sent to the peer verbatim. */
enum class VoiceSignalRejection {
    UNKNOWN_TYPE,
    MISSING_FIELD,
    WRONG_FIELD_TYPE,
    MALFORMED_VOICE_SESSION_ID,
    SDP_EMPTY,
    SDP_TOO_LARGE,
    CANDIDATE_EMPTY,
    CANDIDATE_TOO_LARGE,
    SDP_MID_TOO_LARGE,
    MLINE_INDEX_OUT_OF_RANGE,
}

/**
 * Parses and bounds-checks a `VOICE_*` payload.
 *
 * **Total, and non-throwing.** Every peer-controlled field is read through an accessor that
 * returns null rather than throwing, so no malformed frame can kill the control read loop — the
 * same rule the §2e hardening pass established for `PING`/`PONG` and Phase 1b extended to `HELLO`.
 * PROTOCOL §7.4: a malformed `VOICE_*` frame is dropped, and the control connection survives.
 */
object VoiceSignalCodec {
    sealed class Result {
        data class Parsed(
            val signal: VoiceSignal,
        ) : Result()

        data class Rejected(
            val reason: VoiceSignalRejection,
        ) : Result()
    }

    fun parse(
        type: String,
        payload: JsonObject,
    ): Result =
        when (type) {
            VoiceMessageTypes.OFFER -> parseDescription(payload) { id, sdp -> VoiceSignal.Offer(id, sdp) }
            VoiceMessageTypes.ANSWER -> parseDescription(payload) { id, sdp -> VoiceSignal.Answer(id, sdp) }
            VoiceMessageTypes.ICE -> parseIce(payload)
            VoiceMessageTypes.STATE -> parseState(payload)
            else -> Result.Rejected(VoiceSignalRejection.UNKNOWN_TYPE)
        }

    @Suppress("ReturnCount") // one early-out per PROTOCOL §7.4 field rule, in spec order
    private inline fun parseDescription(
        payload: JsonObject,
        build: (VoiceSessionId, String) -> VoiceSignal,
    ): Result {
        val id = requiredVoiceSessionId(payload) ?: return rejectVoiceSessionId(payload)
        val sdp = stringField(payload, FIELD_SDP) ?: return missingOrWrongType(payload, FIELD_SDP)
        boundedSdp(sdp)?.let { return Result.Rejected(it) }
        return Result.Parsed(build(id, sdp))
    }

    @Suppress("ReturnCount") // one early-out per bound reads clearer than nesting five checks
    private fun parseIce(payload: JsonObject): Result {
        val id = requiredVoiceSessionId(payload) ?: return rejectVoiceSessionId(payload)
        val candidate = stringField(payload, FIELD_CANDIDATE) ?: return missingOrWrongType(payload, FIELD_CANDIDATE)
        if (candidate.isEmpty()) return Result.Rejected(VoiceSignalRejection.CANDIDATE_EMPTY)
        if (candidate.utf8Size() > VoiceBounds.MAX_CANDIDATE_BYTES) {
            return Result.Rejected(VoiceSignalRejection.CANDIDATE_TOO_LARGE)
        }

        // `sdp_mid` is legitimately nullable, so an explicit JSON null is accepted and a missing
        // key is treated the same way. A present-but-wrong-typed value is still a rejection.
        val midEntry = payload[FIELD_SDP_MID]
        val mid: String?
        if (midEntry == null || midEntry is JsonNull) {
            mid = null
        } else {
            val asString =
                (midEntry as? JsonPrimitive)?.takeIf { it.isString }?.content
                    ?: return Result.Rejected(VoiceSignalRejection.WRONG_FIELD_TYPE)
            if (asString.utf8Size() > VoiceBounds.MAX_SDP_MID_BYTES) {
                return Result.Rejected(VoiceSignalRejection.SDP_MID_TOO_LARGE)
            }
            mid = asString
        }

        val index = intField(payload, FIELD_SDP_MLINE_INDEX) ?: return missingOrWrongType(payload, FIELD_SDP_MLINE_INDEX)
        if (index < 0 || index > VoiceBounds.MAX_MLINE_INDEX) {
            return Result.Rejected(VoiceSignalRejection.MLINE_INDEX_OUT_OF_RANGE)
        }
        return Result.Parsed(VoiceSignal.IceCandidate(id, candidate, mid, index))
    }

    @Suppress("ReturnCount")
    private fun parseState(payload: JsonObject): Result {
        val stateRaw = stringField(payload, FIELD_STATE) ?: return missingOrWrongType(payload, FIELD_STATE)
        val state = VoiceWireState.parse(stateRaw)
        val micMuted = booleanField(payload, FIELD_MIC_MUTED) ?: return missingOrWrongType(payload, FIELD_MIC_MUTED)
        val modeRaw = stringField(payload, FIELD_MODE) ?: return missingOrWrongType(payload, FIELD_MODE)

        // PROTOCOL §7.4: `voice_session_id` is null exactly when the sender does not hold one —
        // `idle`, `closed`, and the answerer's `negotiating` intent, where the offerer has not
        // created a generation yet. Whether a null id is *meaningful* for a given `state` is the
        // negotiation table's decision (`VoiceNegotiation`), not the codec's: one rule, one place.
        val idEntry = payload[FIELD_VOICE_SESSION_ID]
        val id: VoiceSessionId?
        if (idEntry == null || idEntry is JsonNull) {
            id = null
        } else {
            val asString =
                (idEntry as? JsonPrimitive)?.takeIf { it.isString }?.content
                    ?: return Result.Rejected(VoiceSignalRejection.WRONG_FIELD_TYPE)
            id = VoiceSessionId.parse(asString) ?: return Result.Rejected(VoiceSignalRejection.MALFORMED_VOICE_SESSION_ID)
        }
        return Result.Parsed(VoiceSignal.State(id, state, micMuted, VoiceMode.parse(modeRaw)))
    }

    private fun boundedSdp(sdp: String): VoiceSignalRejection? =
        when {
            sdp.isEmpty() -> VoiceSignalRejection.SDP_EMPTY
            sdp.utf8Size() > VoiceBounds.MAX_SDP_BYTES -> VoiceSignalRejection.SDP_TOO_LARGE
            else -> null
        }

    private fun requiredVoiceSessionId(payload: JsonObject): VoiceSessionId? =
        stringField(payload, FIELD_VOICE_SESSION_ID)?.let(VoiceSessionId::parse)

    /**
     * Distinguishes "the key is absent or the wrong JSON type" from "the key is a string that is
     * not 32 lowercase hex characters", because the two are different bugs and the diagnostics
     * screen is where someone will be looking for the difference.
     */
    private fun rejectVoiceSessionId(payload: JsonObject): Result.Rejected =
        if (stringField(payload, FIELD_VOICE_SESSION_ID) != null) {
            Result.Rejected(VoiceSignalRejection.MALFORMED_VOICE_SESSION_ID)
        } else {
            missingOrWrongType(payload, FIELD_VOICE_SESSION_ID)
        }

    private fun missingOrWrongType(
        payload: JsonObject,
        key: String,
    ): Result.Rejected =
        if (payload.containsKey(key)) {
            Result.Rejected(VoiceSignalRejection.WRONG_FIELD_TYPE)
        } else {
            Result.Rejected(VoiceSignalRejection.MISSING_FIELD)
        }

    private fun stringField(
        payload: JsonObject,
        key: String,
    ): String? = (payload[key] as? JsonPrimitive)?.takeIf { it.isString }?.content

    /** PROTOCOL fields are typed, not stringly-typed: a quoted number is a wrong type, not an int. */
    private fun intField(
        payload: JsonObject,
        key: String,
    ): Int? = (payload[key] as? JsonPrimitive)?.takeIf { !it.isString }?.intOrNull

    private fun booleanField(
        payload: JsonObject,
        key: String,
    ): Boolean? =
        (payload[key] as? JsonPrimitive)?.takeIf { !it.isString }?.let {
            when (it.content) {
                "true" -> true
                "false" -> false
                else -> null
            }
        }

    const val FIELD_VOICE_SESSION_ID = "voice_session_id"
    const val FIELD_SDP = "sdp"
    const val FIELD_CANDIDATE = "candidate"
    const val FIELD_SDP_MID = "sdp_mid"
    const val FIELD_SDP_MLINE_INDEX = "sdp_mline_index"
    const val FIELD_STATE = "state"
    const val FIELD_MIC_MUTED = "mic_muted"
    const val FIELD_MODE = "mode"
}

/**
 * Bounds are specified in **UTF-8 bytes** (PROTOCOL §7.5), not UTF-16 code units, because that is
 * what the frame actually carries. For ASCII SDP the two agree; for a peer that puts a multi-byte
 * character in a candidate's network-id they do not, and the frame size is the one that matters.
 */
private fun String.utf8Size(): Int = toByteArray(Charsets.UTF_8).size
