package com.ridelink.data.database

import androidx.room.Entity
import androidx.room.Fts4
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * The Room row for one [com.ridelink.core.library.LibraryEntry].
 *
 * The primary key is a synthetic autogenerated `id`, **not** `localEntryId` — Room's external-content
 * FTS4 sync (see [TrackFtsEntity]) requires the content table to be a plain rowid table, and a
 * `TEXT` primary key would defeat that. `localEntryId` is instead a `UNIQUE` index: this phone's own
 * per-row identity (ADR-005 Amendment A1), enforced at the schema level so two rows can never
 * silently coexist for the same [com.ridelink.core.model.LocalEntryId].
 *
 * **`quickId` is deliberately *not* unique, and `locationUri` is** (ADR-005 Amendment A1, this
 * phase's closure-audit CRITICAL finding). `quickId` samples only size plus first/last 64 KiB, so
 * two genuinely different files over 128 KiB can share one — a `UNIQUE` constraint on it, and the
 * `quickId`-keyed `REPLACE`-on-conflict upsert this schema used to have, would silently and
 * irreversibly collapse two different files' rows into one the moment that happened. `locationUri`
 * cannot suffer that: two distinct on-disk locations are, definitionally, two distinct rows.
 *
 * **Phase 3 deliberately does not collapse two rows that turn out to share a `content_hash`
 * either.** FR-010 ("preventing unnecessary transfer of identical files with different names") is
 * about *transfer*, which does not exist until Phase 4/5 — collapsing local library rows today would
 * mean deleting one out from under a local queue/player reference for a requirement Phase 3 has no
 * consumer for yet. Two byte-identical files therefore show as two independent rows in Phase 3's
 * catalogue; real, authoritative duplicate detection for transfer happens in Phase 4/5, keyed on
 * [com.ridelink.core.model.ContentHash] equality once both sides have it — never on `quickId`.
 *
 * `content_hash` is nullable — ADR-005: computed lazily, absent until the background hashing pass
 * reaches this row. A row without one is displayable but not sync/transfer-eligible (Phase 4/5,
 * not Phase 3's concern, but the column exists now because Phase 3 owns the schema).
 */
@Entity(
    tableName = "tracks",
    // Column names below are Room's default mapping of the Kotlin property names (camelCase,
    // no @ColumnInfo override) — localEntryId/quickId/contentHash, not local_entry_id/quick_id/
    // content_hash.
    indices = [
        Index(value = ["localEntryId"], unique = true),
        Index(value = ["locationUri"], unique = true),
        Index(value = ["quickId"]),
        Index(value = ["contentHash"]),
    ],
)
data class TrackEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val localEntryId: String,
    val quickId: String,
    val contentHash: String?,
    val title: String,
    val artist: String,
    val album: String,
    val durationMs: Long,
    val filename: String,
    val codec: String,
    val bitrateKbps: Int,
    val artworkRef: String?,
    val sizeBytes: Long,
    val locationUri: String,
    /** [com.ridelink.core.library.DecodeStatus]'s name — stored as text, mapped at the repository
     *  boundary, the same manual-mapping discipline `network.control.ControlMessages` uses for its
     *  own wire enums rather than a TypeConverter's implicit, easy-to-miss ordinal coupling. */
    val decodeStatus: String,
    val indexedAtMonoUs: Long,
    val lastSeenAtMonoUs: Long,
)

/**
 * External-content FTS4 index over exactly the fields REQUIREMENTS §8/this phase's brief §13
 * require to be searchable: title, artist, album, filename. Room generates the sync triggers that
 * keep this in step with [TrackEntity] automatically — nothing here is ever written to directly.
 *
 * FTS4, not FTS5: Room ships an official `@Fts4` annotation; it has no `@Fts5` equivalent as of the
 * pinned Room version. iOS uses real FTS5 via GRDB — a deliberate, documented per-platform
 * difference in search *engine*, not in search *behaviour* (both are case-insensitive substring/
 * prefix search over the same four fields), so it is not a portability defect.
 */
@Fts4(contentEntity = TrackEntity::class)
@Entity(tableName = "tracks_fts")
data class TrackFtsEntity(
    val title: String,
    val artist: String,
    val album: String,
    val filename: String,
)
