package com.ridelink.data.database

import androidx.room.Entity
import androidx.room.Fts4
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * The Room row for one [com.ridelink.core.library.LibraryEntry].
 *
 * The primary key is a synthetic autogenerated `id`, **not** `quick_id` — Room's external-content
 * FTS4 sync (see [TrackFtsEntity]) requires the content table to be a plain rowid table, and a
 * `TEXT` primary key would defeat that. `quick_id` is instead a `UNIQUE` index: ADR-005's stable
 * pre-hash identity, enforced at the schema level so two rows can never silently coexist for the
 * same content (the FR-010 dedup invariant `core.library.IndexReconciliation` assumes upstream of
 * the database).
 *
 * `content_hash` is nullable — ADR-005: computed lazily, absent until the background hashing pass
 * reaches this row. A row without one is displayable but not sync/transfer-eligible (Phase 4/5,
 * not Phase 3's concern, but the column exists now because Phase 3 owns the schema).
 */
@Entity(
    tableName = "tracks",
    // Column names below are Room's default mapping of the Kotlin property names (camelCase,
    // no @ColumnInfo override) — quickId/contentHash, not quick_id/content_hash.
    indices = [Index(value = ["quickId"], unique = true), Index(value = ["contentHash"])],
)
data class TrackEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val quickId: String,
    val contentHash: String?,
    val title: String,
    val artist: String,
    val album: String,
    val durationMs: Long,
    val filename: String,
    val codec: String,
    val bitrateKbps: Int,
    val artworkRef: String?,
    val sizeBytes: Long,
    val locationUri: String,
    /** [com.ridelink.core.library.DecodeStatus]'s name — stored as text, mapped at the repository
     *  boundary, the same manual-mapping discipline `network.control.ControlMessages` uses for its
     *  own wire enums rather than a TypeConverter's implicit, easy-to-miss ordinal coupling. */
    val decodeStatus: String,
    val indexedAtMonoUs: Long,
    val lastSeenAtMonoUs: Long,
)

/**
 * External-content FTS4 index over exactly the fields REQUIREMENTS §8/this phase's brief §13
 * require to be searchable: title, artist, album, filename. Room generates the sync triggers that
 * keep this in step with [TrackEntity] automatically — nothing here is ever written to directly.
 *
 * FTS4, not FTS5: Room ships an official `@Fts4` annotation; it has no `@Fts5` equivalent as of the
 * pinned Room version. iOS uses real FTS5 via GRDB — a deliberate, documented per-platform
 * difference in search *engine*, not in search *behaviour* (both are case-insensitive substring/
 * prefix search over the same four fields), so it is not a portability defect.
 */
@Fts4(contentEntity = TrackEntity::class)
@Entity(tableName = "tracks_fts")
data class TrackFtsEntity(
    val title: String,
    val artist: String,
    val album: String,
    val filename: String,
)
