#!/usr/bin/env python3
"""Generate protocol/vectors/ordering/ordering_vectors.json.

PROTOCOL §2.1 and §5's command-ordering rules (ADR-010, ADR-024 §3):

  - Playback commands are ordered by the leader-assigned `command_seq`, never by the envelope
    `seq`, never by `msg_id`, never by `sent_at_mono_us`, and never by comparing
    `effective_at_session_us`.
  - `command_seq <= last applied` is dropped: a late duplicate cannot rewind playback.
  - `command_seq == 0` is **not** an ordering value. It marks a follower's *intent* (ADR-024 §3),
    which only the leader may act on.
  - A frame whose `command_seq` contradicts the sender's ADR-010 role is a role violation: an
    authoritative command arriving at the leader, or an intent arriving at a follower. Both are
    dropped, never applied — this is what makes "a follower cannot fabricate an authoritative
    command_seq" a checked property rather than an assumption.

An independent third transcription, not a port of either platform's `CommandOrderGate`. Edit this
generator, never the JSON.

Run:  python3 tools/generate_ordering_vectors.py
"""

from __future__ import annotations

import json
from pathlib import Path

UNASSIGNED = 0


def decide(role: str, last_applied: int | None, incoming: int) -> str:
    if incoming == UNASSIGNED:
        return "INTENT" if role == "LEADER" else "ROLE_VIOLATION"
    if role == "LEADER":
        return "ROLE_VIOLATION"
    if last_applied is None:
        return "ACCEPT"
    if incoming == last_applied:
        return "DUPLICATE"
    if incoming < last_applied:
        return "STALE"
    return "ACCEPT"


def cross_product_rows() -> list[dict]:
    rows = []
    for role in ["LEADER", "FOLLOWER"]:
        for last_applied in [None, 0, 1, 42, 9_007_199_254_740_991]:
            for incoming in [0, 1, 41, 42, 43, 9_007_199_254_740_991]:
                rows.append(
                    {
                        "name": f"{role.lower()}-last-{'none' if last_applied is None else last_applied}-in-{incoming}",
                        "input": {"role": role, "last_applied_seq": last_applied, "incoming_seq": incoming},
                        "expected": {"decision": decide(role, last_applied, incoming)},
                    }
                )
    return rows


def stream_rows() -> list[dict]:
    """Whole streams, so the *applied set* is asserted rather than one decision at a time."""
    streams = [
        ("in-order-stream", "FOLLOWER", [1, 2, 3, 4, 5]),
        ("duplicate-in-the-middle", "FOLLOWER", [1, 2, 2, 3]),
        ("stale-after-a-jump", "FOLLOWER", [1, 5, 2, 6]),
        ("gap-is-not-an-error", "FOLLOWER", [1, 10, 11]),
        ("replayed-tail", "FOLLOWER", [1, 2, 3, 1, 2, 3]),
        ("intent-in-an-authoritative-stream-at-a-follower", "FOLLOWER", [1, 0, 2]),
        ("authoritative-command-arriving-at-the-leader", "LEADER", [1, 2, 3]),
        ("intents-arriving-at-the-leader", "LEADER", [0, 0, 0]),
        ("single-command", "FOLLOWER", [7]),
        ("descending-stream-applies-only-the-first", "FOLLOWER", [9, 8, 7, 6]),
    ]
    rows = []
    for name, role, seqs in streams:
        last_applied: int | None = None
        decisions = []
        applied = []
        for seq in seqs:
            decision = decide(role, last_applied, seq)
            decisions.append(decision)
            if decision == "ACCEPT":
                applied.append(seq)
                last_applied = seq
        rows.append(
            {
                "name": name,
                "input": {"role": role, "incoming_seqs": seqs},
                "expected": {
                    "decisions": decisions,
                    "applied_seqs": applied,
                    "final_last_applied_seq": last_applied,
                },
            }
        )
    return rows


def main() -> None:
    cross = cross_product_rows()
    streams = stream_rows()
    payload = {
        "_comment": (
            "PROTOCOL §2.1/§5 command ordering: (role, last_applied_seq, incoming_seq) -> decision, "
            "as a full cross product, plus whole streams whose applied set is asserted. "
            "command_seq is the sole ordering authority — no vector here carries an envelope seq, a "
            "msg_id or a timestamp, because none of them may influence the answer. Generated by "
            "tools/generate_ordering_vectors.py — an independent third transcription of the rules. "
            "Edit the generator, never this file."
        ),
        "_invariants": [
            "command_seq 0 is never an ordering value: it is INTENT at the leader and ROLE_VIOLATION "
            "at a follower, and it never becomes last_applied_seq.",
            "An authoritative command (command_seq >= 1) arriving at the LEADER is always a "
            "ROLE_VIOLATION — the leader is the only assigner, so it can never be a legitimate "
            "recipient of one.",
            "last_applied_seq never decreases across a stream.",
            "A DUPLICATE or STALE decision never appears in applied_seqs.",
        ],
        "decisions": ["ACCEPT", "DUPLICATE", "STALE", "INTENT", "ROLE_VIOLATION"],
        "unassigned_command_seq": UNASSIGNED,
        "cross_product": cross,
        "streams": streams,
    }
    out = Path(__file__).resolve().parent.parent / "protocol" / "vectors" / "ordering"
    out.mkdir(parents=True, exist_ok=True)
    target = out / "ordering_vectors.json"
    target.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {target} ({len(cross) + len(streams)} rows)")


if __name__ == "__main__":
    main()
