#!/usr/bin/env python3
"""Regenerates `protocol/vectors/session-gate/gate_vectors.json`.

Deliberately an **independent third implementation** of the trust-gate table, in the same spirit
as `generate_identity_vectors.py`: the rules below are transcribed from ADR-019 / ARCHITECTURE §3
and §4.3, not from the Kotlin or Swift source. If this file and either platform disagree, one of
the three is wrong and a laptop unit test says so — which is the whole point.

Edit this generator, never the JSON.

    python3 tools/generate_session_gate_vectors.py
"""

import json
import pathlib

STATUSES = [
    "IDLE", "DISCOVERING", "PAIRING", "CONNECTING", "CONNECTED",
    "RIDE_ACTIVE", "RECONNECTING", "DISCONNECTED", "ENDING", "ERROR",
]

CONTROL_EVENTS = [
    {"kind": "Connected"},
    {"kind": "PeerTrusted"},
    {"kind": "PairingRequired"},
    {"kind": "PairingSucceeded"},
    {"kind": "PairingFailed"},
    {"kind": "HandshakeRefused"},
    {"kind": "LinkLost", "reason": "NETWORK"},
    {"kind": "LinkLost", "reason": "BYE"},
    {"kind": "LinkLost", "reason": "DUPLICATE_CONNECTION"},
    {"kind": "LinkLost", "reason": "USER_ENDED"},
    {"kind": "DuplicateConnectionClosed"},
    {"kind": "ReconnectBudgetExhausted"},
]


def session_event(control_event, status):
    """The FSM event a control event implies, or None for "no transition"."""
    kind = control_event["kind"]

    # ADR-019: `Connected` means the trust gate has already passed. It finishes the walk to
    # CONNECTED and never opens the gate itself.
    if kind == "Connected":
        if status == "CONNECTING":
            return {"kind": "ConnectionEstablished"}
        if status == "RECONNECTING":
            return {"kind": "ReconnectSucceeded"}
        return None

    # The only two ways out of PAIRING: the stored pin matched, or both users confirmed.
    if kind in ("PeerTrusted", "PairingSucceeded"):
        return {"kind": "PairingSucceeded"} if status == "PAIRING" else None

    # A code on screen is not a transition.
    if kind == "PairingRequired":
        return None

    # A pairing that ended without a pin, and a refused handshake, both leave PAIRING.
    if kind in ("PairingFailed", "HandshakeRefused"):
        return {"kind": "PairingRejectedOrTimeout"} if status == "PAIRING" else None

    if kind == "LinkLost":
        reason = control_event["reason"]
        # ADR-015: neither of these is a fault or a transition.
        if reason in ("DUPLICATE_CONNECTION", "USER_ENDED"):
            return None
        # A link that dies mid-pairing is a pairing that did not happen. `LinkLost` is not legal
        # in PAIRING, so the FSM would otherwise wedge there.
        if status == "PAIRING":
            return {"kind": "PairingRejectedOrTimeout"}
        if reason == "NETWORK":
            if status == "CONNECTING":
                return {"kind": "ConnectionFailed"}
            return {"kind": "LinkLost", "reason": "NETWORK"}
        return {"kind": "LinkLost", "reason": "BYE"}

    # ARCHITECTURE §3 rule 6: handed to the FSM so the no-op is recorded rather than invisible.
    if kind == "DuplicateConnectionClosed":
        return {"kind": "DuplicateConnectionClosed"}

    if kind == "ReconnectBudgetExhausted":
        return {"kind": "ReconnectBudgetExhausted"}

    raise AssertionError("unhandled control event: " + kind)


def row_name(control_event, status):
    kind = control_event["kind"]
    if "reason" in control_event:
        kind = kind + "-" + control_event["reason"].lower().replace("_", "-")
    return _kebab(kind) + "-in-" + status.lower().replace("_", "-")


def _kebab(name):
    out = []
    for index, char in enumerate(name):
        if char.isupper() and index > 0:
            out.append("-")
        out.append(char.lower())
    return "".join(out)


def main():
    rows = [
        {
            "name": row_name(event, status),
            "control_event": event,
            "status": status,
            "session_event": session_event(event, status),
        }
        for event in CONTROL_EVENTS
        for status in STATUSES
    ]

    document = {
        "_comment": (
            "The complete trust-gate table (ADR-019): every ControlEvent x every session status, "
            "and the SessionEvent it implies (null = no transition). Both platforms' SessionGate "
            "runs this file, so `Connected` being read as implicit pairing success on one platform "
            "and not the other is a laptop unit-test failure rather than something two phones "
            "discover on a ride. Generated by tools/generate_session_gate_vectors.py - edit the "
            "generator, never this file."
        ),
        "_invariant": (
            "No row whose control_event.kind is Connected may have session_event.kind "
            "PairingSucceeded. That single row is the Phase 1b security bug."
        ),
        "rows": rows,
    }

    out = pathlib.Path(__file__).resolve().parent.parent / "protocol/vectors/session-gate/gate_vectors.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(document, indent=2) + "\n")
    print("wrote " + str(out) + " (" + str(len(rows)) + " rows)")


if __name__ == "__main__":
    main()
